name: CI/CD Pipeline

on:
  push:
    branches:
      - test/test-cicd
  pull_request:
    branches:
      - test/test-cicd

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-24.04
    if: ${{ !startsWith(github.event.head_commit.message, 'draft') && !startsWith(github.event.pull_request.title, 'draft') }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.8.4'

    - name: Build JAR with Maven
      run: mvn clean package -DskipTests=true -U

    - name: Upload the JAR file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: forum-v1.0.jar
        path: target/forum-v1.0.jar

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - name: Download the JAR file from build job
      uses: actions/download-artifact@v4
      with:
        name: forum-v1.0.jar
        path: ./

    - name: Upload the JAR file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: forum-v1.0.jar
        target: /root/project/forum

    - name: Start Service
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          jps -l | grep -E -i 'forum' | awk '{print "kill "$1}' | sh
          nohup java -jar /root/project/forum/forum-v1.0.jar --spring.profiles.active=dev >/dev/null 2>&1 &
          echo 'forum-v1.0 service started successfully.'
