name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# 新提交
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-24.04
    if: ${{ !startsWith(github.event.head_commit.message, 'draft') && !startsWith(github.event.pull_request.title, 'draft') }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: '3.8.4'

    - name: Parse version from pom.xml
      id: parse_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Build JAR with Maven
      run: mvn clean package -DskipTests=true -U

    - name: Upload the JAR file as artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: forum-${{ env.VERSION }}.jar
        path: target/forum-${{ env.VERSION }}.jar

    outputs:
      VERSION: ${{ steps.parse_version.outputs.VERSION }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/master'
    needs: build
    env:
      VERSION: ${{ needs.build.outputs.VERSION }}
    steps:
    - name: Download the JAR file from build job
      uses: actions/download-artifact@v4
      with:
        name: forum-${{ env.VERSION }}.jar
        path: ./

    - name: Upload the JAR file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: forum-${{ env.VERSION }}.jar
        target: /root/project/forum

    - name: Start Service
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd /root/project/forum
          jps -l | grep -E -i 'forum' | awk '{print "kill "$1}' | sh
          rm -rf logs
          nohup java -jar forum-${{ env.VERSION }}.jar --spring.profiles.active=dev >/dev/null 2>&1 &
          echo 'forum-${{ env.VERSION }} service started successfully.'
